version: '3'
services:

  #PHP Service
  app-test61:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app-test61
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - network-test61

  #Nginx Service
  webserver-test61:
    image: nginx:alpine
    container_name: webserver-test61
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - network-test61

  #MySQL Service
  db-test61:
    image: mysql:8.0.29
    container_name: db-test61
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test61
      MYSQL_ROOT_PASSWORD: test61pass
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/my.cnf
    networks:
      - network-test61

#Docker Networks
networks:
  network-test61:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local